// sectorsConfig.js

const sectors = [
    'Manufacturing',
    'Construction materials',
    'Electronic and Optics',
    'Food and Beverage',
    'Bakery & Confectionary',
    'Beverage',
    'Fish & Fish Products',
    'Meat & meat products',
    'Milk & dairy products',
    'other',
    'Sweets and snack food',
    'Furniture',
    'Bathroom/sauna',
    'Bedroom',
    'Childrena room',
    'Kitchen',
    'Living room',
    'office',
    'other(furniture)',
    'Outdoor',
    'Project furniture',
    'Machinery',
    'Machine components',
    'Machine equipments',
    'Manufacture of machinery',
    'Aluminium and steel workboats',
    'Boat/Yatch building',
    'Ship repair and  conversion',
    'Metal structures',
    'Other',
    'Repair and maintenance service',
    'Houses and building',
    'Metal products',
    'Metal works',
    'CNC-machining',
    'Forging, Fasteners',
    'Gas, Plasma, Laser cutting',
    'MIG,TIG, Aluminum welding',
    'Plastic and Rubber',
    'Plastic processing technology',
    'Blowing',
    'Moulding',
    'Plastic welding and processing',
    'Plastic profiles',
    'Printing',
    'Advertising',
    'Book/Periodicals printing',
    'Labelling  and packaging printing',
    'Textile and Clothing',
    'Clothing',
    'Textile',
    'Wood',
    'other(Wood)',
    'Wooden building materials',
    'Wooden houses',
    'Other',
    'Creative industries',
    'Energy technology',
    'Environment',
    'Service',
    'Business services',
    'Engineering',
    'Information Technology and Telecommunications',
    'Data processing, Web portals, E-marketing',
    'Programming, Consultancy',
    'Software, Hardware',
    'Telecommunications',
    'Tourism',
    'Translation services',
    'Transport and Logistics',
    'Air',
    'Rail',
    'Road',
    'Water'
    

    

    
  ];
  
  module.exports = sectors;
  